collections:
  portfolio:
    output: true

defaults:
  -
    scope:
      path: ""

    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "portfolio"

    values:
      layout: "portfolio"
